
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/go-chi/chi"
  version = "4.0.3"

[[constraint]]
  name = "github.com/go-chi/cors"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-chi/docgen"
  version = "1.0.5"

[[constraint]]
  name = "github.com/go-chi/jwtauth"
  version = "4.0.4"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.1"

[[constraint]]
  name = "github.com/go-mail/mail"
  version = "2.3.1"

[[constraint]]
  name = "github.com/go-ozzo/ozzo-validation"
  version = "3.6.0"

[[constraint]]
  name = "github.com/go-pg/migrations"
  version = "6.7.3"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "8.0.6"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jaytaylor/html2text"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mssola/user_agent"
  version = "0.5.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.6.2"

[[constraint]]
  name = "github.com/vanng822/go-premailer"
  version = "1.7.0"
